name: Hello World

on:
  schedule:
    - cron: '*/5 10h20-10h30 * * *'  # Toutes les 5 minutes de 00h00 à 07h00

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello World"
