name: Scheduled Test

on:
  schedule:
    - cron: '10-59/1 14 * * *'  # Planifier toutes les minutes de 14h10 à 15h00

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run Test Script
      run: python test.py
