# Nom de l'ordonnaceur
name: Scraping Workflow

# Parametrage du pas de temps pour le scraping
# On prendra les nouveaux articles toutes les 9h.
# On fait un scrap egalement à chaque push
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */9 * * *'
    # Cette expression signifie :
    # Minute : 0 (c'est-à-dire au début de chaque heure)
    # Heure : toutes les 9 heures (0, 9, 18, etc.)
    # Jour du mois : chaque jour (1-31)
    # Mois : chaque mois (1-12)
    # Jour de la semaine : chaque jour de la semaine (0-6, où 0 est dimanche)

# Parametrage du workflow
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Clonage du dépôt GitHub dans l'environnement d'exécution où le workflow s'exécute.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Instalation des dependances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Execution du scraping
  run_code:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Code
        run: python main.py
  
  # Configuration des parametres git et commit si necessaire
  commit_and_push:
    runs-on: ubuntu-latest
    needs: run_code
    steps:
      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
      
      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto commit from GitHub Actions"
            git push origin main
          else
            echo "No changes to commit."
          fi

        
